name: Deploy editor page
on:
  push:
    branches:
      - main
    paths:
      - apps/editor/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Enable pnpm
        run: corepack enable pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build -F editor
        env:
          VITE_WORKER_EDITOR_ENDPOINT: ${{ vars.WORKER_EDITOR_ENDPOINT }}
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          projectName: simochee-net-editor
          directory: apps/editor/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
