name: Deploy www page
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build -F www
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          projectName: simochee-net
          directory: apps/www/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
